### ISSUE TITLE
java/C# 应该偏向为解释型语言？

### ISSUE THREAD

**Issue by VxCoder** [chinesehuazhou/python-whydo#14]
**Python 为什么没有 main 函数？为什么我不推荐写 main 函数？** 中将java/C#归为编译型语言，个人感觉不恰当。这两者跟python一样，都是基于虚拟机的解释型语言。只是C#/java的解析器没python灵活，必须指定一个入口点。

**Comment by chinesehuazhou** [comment]
一般还是会将它们归为编译型语言吧，因为需要编译器编译成中间代码（虽然不是最终的可执行代机器码）。但由于使用虚拟机执行，也有人称为为“半编译型”
