### ISSUE TITLE
print函数的返回值问题。

### ISSUE THREAD

**Issue by just-createone** [chinesehuazhou/python-whydo#2]
print（1）返回值为None，那1是什么意思？1不是返回值嘛？

**Comment by just-createone** [comment]
重新提问一下，我的意思是为什么print（1）中默认的返回值None不会出现，再次调用print（print（1））时会出现？

**Comment by chinesehuazhou** [comment]
> 重新提问一下，我的意思是为什么print（1）中默认的返回值None不会出现，再次调用print（print（1））时会出现？

才注意到有这个问题，抱歉回复晚了。一般我们把函数/方法中 return 的结果称为“返回值”。返回值是可以赋值给变量的，例如 a=print(1)，这里print ()函数的返回值被赋值给了变量a，print (a)输出a的值就是1。你的例子只是没有写赋值给a这一步，但是外层的print是取到了内层函数的返回值none的
